# Advent of Code Binaries
cc_binary(
  name = "aoc_2015_1",
  srcs = ["advent_of_code/2015/1/main.cpp"],
  deps = [
    "//lib:aoc-file-io"
  ]
)

cc_binary(
  name = "aoc_2015_2",
  srcs = ["advent_of_code/2015/2/main.cpp"],
  deps = [
    "//lib:aoc-file-io",
    "//lib:string-ops",
  ]
)

# LeetCode Binaries
cc_binary(
  name = "leet1",
  srcs = ["leetcode/1.cpp"],
)
