cc_library(
    name = "aoc-file-io",
    srcs = ["aoc_file_io.cpp"],
    hdrs = ["aoc_file_io.h"],
    visibility = ["//main:__pkg__"],
)

cc_library(
    name = "string-ops",
    srcs = ["string_ops.cpp"],
    hdrs = ["string_ops.h"],
    visibility = ["//main:__pkg__"],
)

cc_library(
    name = "leetcode-ds",
    hdrs = ["leetcode-ds.h"],
    visibility = ["//main:__pkg__"],
)
